# This is the configuration file to run the cellranger pipeline on the Weizmann cluster/ AWS S3. 

# Required:
project_name: 

# Required:
id: 

# Optional:
donor:                                                                                                      

# Optional:
seq_run:                                                                                                     

# Required for count pipeline: (usually named after the prefix in the fastqs files)
sample_name: 

# Default: project_name/Output_Files
output_destination:                                                                                      

# Default: whatever when using module load into the path file
aligner_software_path:                                                                                   

# Default: refdata-gex-mm10-2020-A
alignment_ref_genome_file:                                                                               

# Default:
alignment_ref_vdj_file:                                                                                  

# Default: /home/labs/nyosef/yoavnah/CellRangerIDE/const_files/transcriptome
alignment_ref_genome_path:                                                                               

# Required:
weizmann_user:                                                                                           

# Optional: if you are not using AWS S3 this one is not necessary
s3_access_file:                                                                                                                                                                                     

# Required:
Sample_sheet_address:                                                                                           

# Default: /home/labs/nyosef/yoavnah/CellRangerIDE/Projects/yoav/OutputFiles/{donor}_{seq_run}_run.sh
shell_file:                                                                                              

# Required: Choose between 'feature_barcode' or 'cmo_barcode'
multiplexing_method: 

# Required:
fastq_path: 
  - 
  - 

# Required:
fastq_folders_name:
  - #Add the name of the folder respectively to the fastq_path here 
  - #Add the name of the folder respectively to the fastq_path here

# Default: any
lanes_used:
  - #Add the lanes used for the fastq files here
  - #Add the lanes used for the fastq files here
  - #Add the lanes used for the fastq files here

# Optional:
physical_library_id:
  - #Add the physical library id here
  - #Add the physical library id here
  - #Add the physical library id here

# Required:
feature_type:
  - #Add the feature type here
  - #Add the feature type here

# Optional:
subsample_rate:
  - #Add the subsample rate here
  - #Add the subsample rate here
  - #Add the subsample rate here


# Optional: only if you are using the feature_reference
feature_reference_csv:  #/home/labs/nyosef/yoavnah/CellRangerIDE/const_files/Shlomit_weeks_HTO_ref.csvHTO_feature_type

# Required: (if feature_reference_csv wasn't given)
hto_id:
  - #Add hashing ID 
  - #Add hashing ID 
  - #Add hashing ID 
  - #Add hashing ID

# Default: hto_names = hto_id 
hto_names:
  - 
  - 
  - 
  - 

# Default: 'R2' 
hto_read:
  - 
  - 
  - 
  - 

# Default: '5PNNNNNNNNNN(BC)' 
hto_pattern:
  - 
  -
  -
  -

# Required 
hto_sequence:
  - 
  - 
  - 
  - 

# Default: Antibody Capture 
HTO_feature_type:
  - 
  -
  -
  -