# This is the configuration file to run the cellranger pipeline which creates annotated data files for multiple samples!

############# Option 1 ############
# Required: 
INCPM_link: https://stefan.weizmann.ac.il/users/ny/nyosef/20241127_LH00211_0190_B2252TLLT1/

# Default: File_Path/INCPM
INCPM_directory: Default

############# Option 2 ############
# Required:
fastq_path: 
  - /home/labs/nyosef/Collaboration/Shlomit_scGEX_Oct2023/231019_A00929_1107_BHLLWJDRX3/li/lireich/231019_A00929_1107_BHLLWJDRX3/AT_LP_EpCAM- #Add the path to the fastq files here 
  - /home/labs/nyosef/Collaboration/Shlomit_scGEX_Oct2023/231019_A00929_1107_BHLLLWJDRX3/li/lireich/231019_A00929_1107_BHLLWJDRX3/CMO_AT_LP_EpCAM- #Add the path to the fastq files here

# Default: refdata-gex-mm10-2020-Apwd
alignment_ref_genome_file: Default

# Required: true or false
create_bam: true

# Required: usually named after the prefix in the fastqs files
sample_name: 
  - B16

# Required: (named after the fastqs folder)
fastq_folders_name:
  - AT_LP_EpCAM
  - CMO_AT_LP_EpCAM

# Default: any
lanes_used: 
  - Default
  - 

# Required, options: 'feature_barcode' or 'cmo_barcode' (for now...)
multiplexing_method: feature_barcode

################ Feature Barcode Section ################

# Optional: only if you are using the feature_barcode as your multiplexing_method 
feature_reference_csv: Default

# Required: choose from the next list respectively to the fastq order: gene expression, Antibody Capture.
feature_types:
  - Gene Expression
  - Multiplexing Capture

# Required: (if feature_barcode was not given)
hto_id:
  -   #Add hashing ID 
  -   #Add hashing ID 
  -   #Add hashing ID 
  -   #Add hashing ID

# Default: hto_names = hto_id 
hto_names:
  - Default
  - 
  - 
  - 

# Default: 'R2' 
hto_read:
  - Default
  - 
  - 
  - 

# Default: '5PNNNNNNNNNN(BC)' 
hto_pattern:
  - Default
  -
  -
  -

# Required (if feature_reference_csv wasn't given)
hto_sequence:
  - AACCTTTGCCACTGC
  - GTCCGACTAATAGCT
  - CAGGTTGTTGTCATT
  - TATTTCCACCCGGTC

# Default: Antibody Capture 
HTO_feature_type:
  - Default
  -
  -
  -


############# CMO Section #################

# Optional: only if you are using the cmo_barcode as your multiplexing_method 
cmo_barcode_csv: Default

# Required (if cmo_barcode_csv wasn't given)
sample_id_cmo:
  - AT_LP_EpCAM-Naive2
  - AT_LP_EpCAM-Naive3
  - AT_LP_EpCAM-Naive147
  - AT_LP_EpCAM-Naive150

# Required (if cmo_barcode_csv wasn't given)
cmo_id:
  - CMO309
  - CMO310
  - CMO311
  - CMO312

##### Demultiplexing section #####
##### End of Demultiplexing section ####