# This is the configuration file to run the cellranger pipeline which creates creates customized reference transcriptomes for you alignment!

# Pay attention you can add one genome at the time for each run

# Required
original_fasta_file_path:

# Required
customized_fasta_file_path:

# Required
fasta_of_new_gene:

# Required 
original_gtf_file_path:

# Required
customized_gtf_file_path:

# Required
gtf_of_new_gene:
