# This is the configuration file to run the cellranger pipeline on the Weizmann cluster/ AWS S3. 

# Required:
id: 318674249

# Required:
donor: 591C                                                                                                     

# Required:
seq_run: 003                                                                                                    

# Default: project_name/Output_Files
output_destination: Default                                                                                     

# Default: whatever when using module load into the path file
aligner_software_path: Default                                                                                  

# Default: refdata-gex-GRCh38-2020-A
alignment_ref_genome_file: Default                                                                              

# Default:
alignment_ref_vdj_file: Default                                                                                 

# Default: /home/labs/nyosef/yoavnah/CellRangerIDE/const_files/transcriptome
alignment_ref_genome_path: Default                                                                              

# Required:
weizmann_user: yoavnah                                                                                          

# Optional: if you are not using AWS S3 this one is not necessary
s3_access_file:                                                                                                 

# Required:
project_name: nir                                                                                               

# Required:
Sample_sheet_address:                                                                                           

# Default: /home/labs/nyosef/yoavnah/CellRangerIDE/Projects/yoav/OutputFiles/{donor}_{seq_run}_run.sh
shell_file: Default                                                                                             

# Ignore:
python_env_version: immune_aging.py_env.v4                                                                      

# Ignore:
r_env_version: immune_aging.r_env.v1                                                                           

# Ignore:
r_setup_version: immune_aging.R_setup.v2                                                                        

# Required:
fastq_path: 
  - /home/labs/nyosef/yoavnah/NovaSeqX-B/Fastqs/li/lireich/20240515_LH00211_0021_B2233L7LT1/FastQC/B16_GEX #Add the path to the fastq files here 
  - /home/labs/nyosef/yoavnah/NovaSeqX-B/Fastqs/li/lireich/20240515_LH00211_0021_B2233L7LT1/FastQC/B16_HASH #Add the path to the fastq files here

# Required:
fastq_folders_name:
  - B16_GEX #Add the name of the folder respectively to the fastq_path here 
  - B16_HASH #Add the name of the folder respectively to the fastq_path here

# Default: any
lanes_used:
  - any #Add the lanes used for the fastq files here
  - any #Add the lanes used for the fastq files here
  - any #Add the lanes used for the fastq files here

# Optional:
physical_library_id:
  - #Add the physical library id here
  - #Add the physical library id here
  - #Add the physical library id here

# Required:
feature_type:
  - gene expression #Add the feature type here
  - gene expression #Add the feature type here

# Optional:
subsample_rate:
  - #Add the subsample rate here
  - #Add the subsample rate here
  - #Add the subsample rate here
